# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x08payments\"b\n\x10\x43reatePaymentReq\x12\x12\n\nbooking_id\x18\x01 \x01(\x05\x12\x19\n\x11\x62ooking_reference\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"G\n\x10\x43reatePaymentRes\x12\x12\n\npayment_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2Y\n\x0ePaymentService\x12G\n\rCreatePayment\x12\x1a.payments.CreatePaymentReq\x1a\x1a.payments.CreatePaymentResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPAYMENTREQ']._serialized_start=27
  _globals['_CREATEPAYMENTREQ']._serialized_end=125
  _globals['_CREATEPAYMENTRES']._serialized_start=127
  _globals['_CREATEPAYMENTRES']._serialized_end=198
  _globals['_PAYMENTSERVICE']._serialized_start=200
  _globals['_PAYMENTSERVICE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
